### ISSUE TITLE
Can you open the LIB Folder‘s W5500 dirvers source file？

### ISSUE THREAD

**Issue by frankgp** [thanhtam-h/soem-w5500-rpi#1]

**Comment by thanhtam-h** [comment]
I will open it some time later. 
Anyway, current library does not have any limit, I will have guide how to rout hardware soon.

**Comment by frankgp** [comment]
Thanks a lot for your reply!
I will wait for them!
Thanks again!

**Comment by TCWilliamson** [comment]
Any chance of this happening soon?

I'd like to try port it over to the NanoPI Neo!
