### ISSUE TITLE
can it work on beaglebone black？

### ISSUE THREAD

**Issue by lichaowuwei** [thanhtam-h/soem-w5500-rpi#11]
can this soem work on beaglebone black？
Thanks and regards

**Comment by thanhtam-h** [comment]
yes, I have made another driver for BBB, I may share it later.

**Comment by lichaowuwei** [comment]
thanks， by the way， could i use  shared memory to instead of recv and send for skb_buff between driver and master？ thanks and regards ------------------ 原始邮件 ------------------
发件人: "Tam Ho"<notifications@github.com>
发送时间: 2019年7月19日(星期五) 下午3:01
收件人: "thanhtam-h/soem-w5500-rpi"<soem-w5500-rpi@noreply.github.com>;
抄送: "lichaowuwei"<lichaowuwei@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [thanhtam-h/soem-w5500-rpi] can it work on beaglebone black？ (#11)



yes, I have made another driver for BBB, I may share it later.
 
&mdash;

**Comment by thanhtam-h** [comment]
you can look at naive drivers of EtherLAB master for reference, it is out of this project.
I will close this issue.

**Comment by rayaanahmed46** [comment]
> yes, I have made another driver for BBB, I may share it later.

Hi can you share it?
