### ISSUE TITLE
PDO mapping for Ezi-Servo Fastech Drive

### ISSUE THREAD

**Issue by thuongtrannc** [thanhtam-h/soem-w5500-rpi#15]
First of all, I would like to thank you for your valuable works.

Recently, I try to control Ezi-Servo Fastech Drive with your introduction. It can turn on and hold the motor. But it seems do not map the PDO correctly in the drive. So it can not change the mode of operation such as Position Profile, Cyclic Sync Mode, ... At this time, I think the Control Word and Status Word mapping in pdo_def.h file is correct. That why the motor can turn on and hold. But other mappings are incorrect.

I saw you have been controlled the motor of Fastech on a Youtube video. Could you please upload the source code to a repository on Github or send me an email in private? 

Actually, it takes me around one week to find and debug the error and change pdo_def.h file but it still doesn't work.

Thank you so much for your works one more time!

**Comment by thanhtam-h** [comment]
Hi,
Provide your email address or send a request to my email mophong@gmail.com, I will share Ezi example
