### ISSUE TITLE
Xenomai task/thread APIs

### ISSUE THREAD

**Issue by tuantdang** [thanhtam-h/soem-w5500-rpi#19]
In osal.c use still use pthread from Linux
I think it is better if you use set of task management of Xenomai such as rt_task_create, rt_task_start, ...

**Comment by tuantdang** [comment]
Does it looks like Xenomai 3 version porting from SOEM 1.3.1
and RT version from 1.3.0?

**Comment by thanhtam-h** [comment]
osal_thread_create and osal_thread_create_rt in osal.c will not be used so they are not adapted to Xenomai task, only time related functions were ported. 
Picat xenomai version use SOEM 1.4.0 while Picat preempt-rt use SOEM 1.3.0 (popular revision)
