### ISSUE TITLE
Do you have any w5500 shield board for rpb 3+?

### ISSUE THREAD

**Issue by zhouq0725** [thanhtam-h/soem-w5500-rpi#2]
Will you provide w5500 board like [PIGATOR Ethernet](http://busware.de/tiki-index.php?page=PIG_ETH)?

**Comment by thanhtam-h** [comment]
Yes and No. I have the shield board but this is for realtime EtherCAT, not for generic Ethernet.
The  shield works for any rpi version. I will write hardware diy soon
With **rpi1**:
![shield-rpi1 - small](https://user-images.githubusercontent.com/32671131/41087027-9602c02c-6a76-11e8-8dc6-c9c5af1b009f.jpg)

With **rpi0 (and 0-W)**:
![shield-rpi0 -small](https://user-images.githubusercontent.com/32671131/41087070-ad198a66-6a76-11e8-9eea-9422d8754e63.jpg)

And **rpi2,3 (and 3b+)**:
![shield-rpi23 - small](https://user-images.githubusercontent.com/32671131/41087113-c8deb780-6a76-11e8-9123-72f1f7479496.jpg)

**Comment by zhouq0725** [comment]
Great. How can i buy it?

**Comment by thanhtam-h** [comment]
You may follow at website www.simplerobot.net
