### ISSUE TITLE
Usage with a cython wrapper.

### ISSUE THREAD

**Issue by Roiki11** [thanhtam-h/soem-w5500-rpi#20]
Hi,

Would it be possible to use a cython wrapper for python for writing user applications? I find c to be a bit hard to use.

The wrapper in question: https://github.com/bnjmnp/pysoem

**Comment by thanhtam-h** [comment]
I think it is possible with some extra works. You may try.

**Comment by Roiki11** [comment]
I see. I assume the C api is untouched so the fuction calls should be the same? Or is there something different there compared to normal SOEM?

**Comment by thanhtam-h** [comment]
The difference is the driver for W5500 Ethernet chip, but it lies at very low level that you may not need to touch.

**Comment by Roiki11** [comment]
Thanks. I think I'll give it a try when I get the hardware for it.
