### ISSUE TITLE
Can U add some delay for link？

### ISSUE THREAD

**Issue by frankgp** [thanhtam-h/soem-w5500-rpi#6]
If I connected the RESET pin for W5500 from RPi3. 
always cannot findout the slaves.

Because the LINK-UP is slowly.

There are 2 slaves.  1-OMRON NX-ECC203
                              2-OMRON GX-MD1618

**Comment by thanhtam-h** [comment]
Did you try to increase EC_TIMEOUTRET3 in 'soem/ethercattype.h' and rebuild soem lib? Currently I  set it to 200ms.  So far I has tested with several drives like Maxon MAXPOS, Servotronix, Elmo Gold, Fastech Ezi,..

**Comment by thanhtam-h** [comment]
frankgp, 
I have updated driver file to add one more function:

**int wiznet_hw_config(uint32_t spi_clkDiv, int startup_rst, uint32_t link_wait_us)**

You now can control:
- SPI clock (3 possible speeds include 31.25 MHz(default), 15.625 MHz and 7.8125 MHz
- RESET at startup or NOT
- waiting after RESET if enabled
You can call this function any place just before calling "ec_init". 
For more details, read description in wiznet_drv.h file and in updated examples.
Cheers

**Comment by frankgp** [comment]
Thanks a lot!  
It's OK!  

thanks again!
