### ISSUE TITLE
How to get an EtherCAT slave?

### ISSUE THREAD

**Issue by littleggghost** [thanhtam-h/soem-w5500-rpi#7]
Hi, @thanhtam-h 
Thanks for your share and we all know how to make an EtherCAT master now, but here the question is: How to make an EtherCAT slave that can test the communication? I can't check the communication if no slave runs. 
Could we build a slave on rpi or if there is any kind of slave board on sale?
Hoping your good progress on slave that can achieve a close loop of EtherCAT!
Thanks again.

**Comment by thanhtam-h** [comment]
If you read post on my blog you will see that I recommend to use XMC4800 Relax kit. It is cheap and easy to use, http://www.simplerobot.net/2018/06/rpi-ethercat-master-picat.html
This project is only for master development, slave development is out of its scope

**Comment by littleggghost** [comment]
I thought you would build a new repository for slave, but now it seems we don't need to. The Infineon might be more easy to use.
