### ISSUE TITLE
Is the Beckhoff PLC necessary?

### ISSUE THREAD

**Issue by littleggghost** [thanhtam-h/soem-w5500-rpi#8]
I noticed that there has an Beckoff PLC in your video, and as I know it is used for generating the config file (XML) about network topology.
Has the xml file been included in repository? Or I have to generate it myself.

**Comment by thanhtam-h** [comment]
That isn't PLC, it is just simply an IO slave device. It does nothing with xml generation, you absolutely don't need it for working. Read other post on my blog simplerobot.net

**Comment by littleggghost** [comment]
Then forgive my ignorance!
